# Problem 1

In [17]:

import numpy as np

y = np.random.randint(0, 10, size=(5))

print(y)

print(f"Matris boyutu: {y.shape}")

print(y)

yenimatris = matris.reshape(5, 1)

print(yenimatris)

print(f"Yeni Matris boyutu: {yenimatris.shape}")


print(f"Matrisin boyut sayısı:", y.ndim)


[5 9 5 6 4]
Matris boyutu: (5,)
[5 9 5 6 4]
[[1]
 [3]
 [5]
 [7]
 [9]]
Yeni Matris boyutu: (5, 1)
Matrisin boyut sayısı: 1


# Problem 2

In [6]:
import numpy as np

matris = np.arange(1, 10, 2).reshape(5, 1)

print(matris)

x = matris[:3]
y=matris[2:]

print(x)

print(y)
 
birlesikMatris = np.concatenate((x, y), axis=1)


print(birlesikMatris)

[[1]
 [3]
 [5]
 [7]
 [9]]
[[1]
 [3]
 [5]]
[[5]
 [7]
 [9]]
[[1 5]
 [3 7]
 [5 9]]


# Problem 3

In [7]:

import numpy as np

z = np.random.randint(5, 100, size=(5, 2)) * 2
print(z)


print(f"Matris boyutu: {z.shape}")
print(f"Matris eleman sayısı: {z.size}")
print(f"Matris boyut sayısı: {z.ndim}")
print(f"Matris elemanlarının veri tipi: {z.dtype}")


[[ 66  26]
 [116 148]
 [138  68]
 [194  14]
 [142  10]]
Matris boyutu: (5, 2)
Matris eleman sayısı: 10
Matris boyut sayısı: 2
Matris elemanlarının veri tipi: int32
